[env:lilygo-t-a7670g-s3]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_build.f_flash = 80000000L
board_build.flash_mode = qio

build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DLV_CONF_INCLUDE_SIMPLE
  -I include
  -I src
  -DUSER_SETUP_LOADED=1
  -DILI9341_2_DRIVER=1
  -DTFT_WIDTH=240
  -DTFT_HEIGHT=320
  -DTFT_MISO=13
  -DTFT_MOSI=11
  -DTFT_SCLK=12
  -DTFT_CS=10
  -DTFT_DC=9
  -DTFT_RST=8
  -DTFT_BL=14
  -DTOUCH_CS=21
  -DSPI_FREQUENCY=40000000
  -DSPI_READ_FREQUENCY=20000000
  -DSPI_TOUCH_FREQUENCY=2500000

lib_deps =
  lvgl/lvgl@^9.2.0
  bodmer/TFT_eSPI@^2.5.43
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
  bblanchon/ArduinoJson@^7.2.0
  tzapu/WiFiManager@^2.0.17
  vshymanskyy/StreamDebugger@^1.0.1
  vshymanskyy/TinyGSM@^0.12.0
