/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfirmemailRouteImport } from './routes/confirmemail'
import { Route as ForgotpasswordRouteImport } from './routes/forgotpassword'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ApiPublicDeviceSosRouteImport } from './routes/api/public/device.sos'
import { Route as ApiPublicDeviceSyncRouteImport } from './routes/api/public/device.sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmemailRoute = ConfirmemailRouteImport.update({
  id: '/confirmemail',
  path: '/confirmemail',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotpasswordRoute = ForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceSosRoute = ApiPublicDeviceSosRouteImport.update({
  id: '/api/public/device/sos',
  path: '/api/public/device/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceSyncRoute = ApiPublicDeviceSyncRouteImport.update({
  id: '/api/public/device/sync',
  path: '/api/public/device/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/confirmemail': typeof ConfirmemailRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/device/sos': typeof ApiPublicDeviceSosRoute
  '/api/public/device/sync': typeof ApiPublicDeviceSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/confirmemail': typeof ConfirmemailRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/device/sos': typeof ApiPublicDeviceSosRoute
  '/api/public/device/sync': typeof ApiPublicDeviceSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/confirmemail': typeof ConfirmemailRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/device/sos': typeof ApiPublicDeviceSosRoute
  '/api/public/device/sync': typeof ApiPublicDeviceSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/confirmemail'
    | '/forgotpassword'
    | '/reset-password'
    | '/api/public/device/sos'
    | '/api/public/device/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/confirmemail'
    | '/forgotpassword'
    | '/reset-password'
    | '/api/public/device/sos'
    | '/api/public/device/sync'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/confirmemail'
    | '/forgotpassword'
    | '/reset-password'
    | '/api/public/device/sos'
    | '/api/public/device/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  ConfirmemailRoute: typeof ConfirmemailRoute
  ForgotpasswordRoute: typeof ForgotpasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicDeviceSosRoute: typeof ApiPublicDeviceSosRoute
  ApiPublicDeviceSyncRoute: typeof ApiPublicDeviceSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmemail': {
      id: '/confirmemail'
      path: '/confirmemail'
      fullPath: '/confirmemail'
      preLoaderRoute: typeof ConfirmemailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotpassword': {
      id: '/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof ForgotpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/sos': {
      id: '/api/public/device/sos'
      path: '/api/public/device/sos'
      fullPath: '/api/public/device/sos'
      preLoaderRoute: typeof ApiPublicDeviceSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/sync': {
      id: '/api/public/device/sync'
      path: '/api/public/device/sync'
      fullPath: '/api/public/device/sync'
      preLoaderRoute: typeof ApiPublicDeviceSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  ConfirmemailRoute: ConfirmemailRoute,
  ForgotpasswordRoute: ForgotpasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicDeviceSosRoute: ApiPublicDeviceSosRoute,
  ApiPublicDeviceSyncRoute: ApiPublicDeviceSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
