// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvogmfjpfndrixkpdodd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2b2dtZmpwZm5kcml4a3Bkb2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0OTY3MzAsImV4cCI6MjA4NDA3MjczMH0.ogYofumhWNQmdy0Rgyx7TEHIbEyRV-WgwU4FXBDnWYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});